version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hd-dashboard
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
        
  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  database_data:
    